# Generated by Django 5.0.14 on 2025-05-24 17:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryID', models.IntegerField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=50)),
                ('CategoryDescription', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Coupouns',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Code', models.CharField(max_length=20, unique=True)),
                ('method', models.CharField(default='01', max_length=2)),
                ('DiscountPercent', models.CharField(default='01', max_length=2)),
                ('ValidFrom', models.DateTimeField(default=datetime.datetime.now)),
                ('ISActive', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Addressline1', models.CharField(max_length=255)),
                ('Addressline2', models.CharField(max_length=255, null=True)),
                ('CustomerState', models.CharField(max_length=50)),
                ('Postalcode', models.CharField(max_length=20)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('GSt', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('DocheaderNo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Beforetax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Aftertax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Paymentstatus', models.CharField(default='Unpaid', max_length=20)),
                ('BillingAddress', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('role', models.CharField(max_length=10, null=True)),
                ('action', models.CharField(max_length=4, null=True)),
                ('Created', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('DocNo', models.IntegerField(primary_key=True, serialize=False)),
                ('PaymentMethod', models.CharField(max_length=4)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PayementDate', models.DateTimeField(default=datetime.datetime.now)),
                ('PaymentStatus', models.CharField(max_length=6)),
                ('InvoiceNO', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AKC.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ProductID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=50)),
                ('ProductDesc', models.CharField(max_length=255)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Imageurl', models.ImageField(upload_to='static/')),
                ('Added', models.DateTimeField(default=datetime.datetime.now)),
                ('CategoryID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AKC.category')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceDetails',
            fields=[
                ('DocheaderNo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('GST', models.CharField(max_length=30)),
                ('InvNo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AKC.invoice')),
                ('ProductID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AKC.products')),
                ('UserID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AKC.users')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='UserID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AKC.users'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('CartID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Added', models.DateTimeField(default=datetime.datetime.now)),
                ('ProductID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AKC.products')),
                ('UserID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AKC.users')),
            ],
        ),
    ]
