# Generated by Django 5.0.14 on 2025-06-08 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AKC', '0002_rename_firstname_users_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Imageurl',
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='AKC.products')),
            ],
        ),
    ]
