# Generated by Django 5.0.14 on 2025-06-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AKC', '0003_remove_products_imageurl_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
    ]
